export const AMERICAN_JAM_FEED_URL =
    'https://americanparkour.com/?post_type=tribe_events&ical=1&eventDisplay=list&iframe=1';

export const EUROPE_JAM_FEED_URL =
    'https://calendar.apiboomtech.com/api/published_calendar?comp_id=comp-l1qi3qyf&instance=XVRQxzlpaXQDRm9amc1mrF8cLMhCpTD1QLYdt2jqPiY.eyJpbnN0YW5jZUlkIjoiNTc4ZmY5NjctZWRjNy00MjgxLThkZTItMGY0ZTlhYzAzNDkwIiwiYXBwRGVmSWQiOiIxM2I0YTAyOC0wMGZhLTcxMzMtMjQyZi00NjI4MTA2YjhjOTEiLCJzaWduRGF0ZSI6IjIwMjYtMDctMDFUMDg6NTM6MDEuMDQ1WiIsInZlbmRvclByb2R1Y3RJZCI6IlByZW1pdW0iLCJkZW1vTW9kZSI6ZmFsc2UsImFpZCI6ImY4ZGU0NzBiLTE4YTgtNGJkYy04ZWU5LTM2MDU1MTU0ODJlNyIsInNpdGVPd25lcklkIjoiMGY2ZmRjOGItMjE2My00NWVkLWE0YzAtZjJkNGM5M2U1NmRjIiwiYnMiOiJ3Q0RSMkRJTkdaY0lvckpBcUNqd09ELXA3a2txM19ON3FYOVFlcmRPRWg4Iiwic2NkIjoiMjAyMi0wNC0wOFQxMzo0MTowNy4yOTdaIn0&originCompId=&time_zone=Europe%2FAmsterdam';
