export const movies = [
	{
		id: 1,
		title: "Jump London",
		year: "2003",
		description: "The documentary that introduced parkour to the world, featuring Sébastien Foucan and other founding traceurs.",
		thumbnail: "https://image.tmdb.org/t/p/original/mSknYoFSBB6o8HeeCTojq3CERgd.jpg",
		videoId: "l8fSXGP9wvQ",
		type: "movie",
		duration: "60m",
		trakt: "https://trakt.tv/movies/jump-london-2003",
		creators: ["Channel 4", "Mike Christie"],
		starring: ["Sébastien Foucan"]
	},
	{
		id: 2,
		title: "Jump Britain",
		year: "2005", 
		description: "The follow-up to Jump London, showcasing British traceurs and the growth of parkour in the UK.",
		thumbnail: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eTMM80n6xFiCwUdNYHEnxEP5QWb.jpg",
		videoId: "2TJurAP9l-Q",
		type: "movie",
		duration: "60m",
		trakt: "https://trakt.tv/movies/jump-britain-2005",
		creators: ["Channel 4", "Mike Christie"],
		starring: ["Sébastien Foucan"]
	},
	{
		id: 3,
		title: "Sole Destroyer",
		year: "2020",
		description: "The Motus Projects athletes push their physical and mental limits in this raw documentary about the evolving sport of parkour. Through elation, stress, injury and laughter, their friendship drives their success.",
		thumbnail: "https://image.tmdb.org/t/p/original/bizGkp2qchu73MNy9Vlh4KW7pQK.jpg",
		videoId: "VlM7bOegiIg",
		type: "movie",
		duration: "40m",
		trakt: "https://trakt.tv/movies/sole-destroyer-2020",
		creators: ["The Motus Projects", "Giles Campbell Longley"],
		starring: [
			"Kelan Ryan",
			"Jordan Tyler Lea",
			"Johnstone Macpherson-Stewart",
			"Luke Stones",
			"George McGowan",
			"Joseph Marx",
			"Robbie Griffith",
			"Max Barker"
		]
	},
	{
		id: 4,
		title: "Amsterdam Is Dead",
		year: "2024",
		description: "AMSTERDAM IS DEAD a Parkour Film aiming to revive this city's lost street parkour scene. Documentaire door Fé Amsterdam.",
		thumbnail: "https://image.tmdb.org/t/p/original/8jJ0IEc24tC1w24niLc2c343YPi.jpg",
		videoId: "lJX3DUlSj4M",
		type: "movie",
		duration: "48m",
		trakt: "https://trakt.tv/movies/amsterdam-is-dead-2024",
		creators: ["Fé Amsterdam", "Safier Elzinga", "Dave Alvar"],
		starring: [
			"Jan Simon",
			"Naël Saint-Paul",
			"Twan de Wilde",
			"Maurits Dorren",
			"Safier Elzinga",
			"Sjoerd Rensma",
			"Bram Looijen",
			"Abel Marce",
			"Vic Kooy",
			"Wieger Hoekstra",
			"Liziano Ostina",
			"Silver Moscou",
			"Francesco Kamstra",
			"Dave Alvar",
			"Tobias Roest"
		]
	},
	{
		id: 5,
		title: "Roof Culture Asia",
		year: "2017",
		description: "Team Storror push Parkour to the rooftops of Asian megacities, filming guerilla-style while exploring the drive, struggles, and preparation behind making impossible \"leaps of faith\" possible.",
		thumbnail: "https://image.tmdb.org/t/p/original/aeAe6WOKXROmmXySeZN6dWccWPX.jpg",
		externalUrl: "https://storrorplus.storror.com/programs/rca?cid=4256061",
		paid: true,
		provider: "STORROR+",
		price: "€8",
		type: "movie",
		duration: "1h 53m",
		trakt: "https://trakt.tv/movies/roof-culture-asia-2017",
		creators: ["STORROR"],
		starring: [
			"Benj Cave",
			"Toby Segar",
			"Max Cave",
			"Callum Powell",
			"Sacha Powell",
			"Richard Ferreday",
			"Drew Taylor",
			"Joshua Burnett-Blake",
			"Giles Campbell Longley"
		]
	},
	{
		id: 6,
		title: "S.O.L",
		year: "2022",
		description: "S.O.L is a parkour tour film with the carefree vibe of 2010s summer edits, focusing less on moves and more on friendship, support, and shared training moments.",
		thumbnail: "/images/posters/the-motus-projects-sol-poster.jpg",
		videoId: "Tswad8jCgaM",
		type: "movie",
		duration: "1h 12m",
		creators: ["The Motus Projects", "Max Barker", "Kelan Ryan", "Sam Sutherland"],
		starring: [
			"Travis Verkaik",
			"Rachel Gough",
			"Ethan Rudd",
			"Joseph Marx",
			"Sam Sutherland",
			"Kelan Ryan",
			"Johnstone Macpherson-Stewart",
			"George McGowan",
			"Max Barker",
			"Robbie Griffith"
		]
	},
	{
		id: 7,
		title: "People in Motion",
		year: "2012",
		description: "Cedric Dahl traveled the US west coast with 5 parkour practitioners who shared a passion for movement. This film documents the experience over 9 months.",
		thumbnail: "https://image.tmdb.org/t/p/original/4WiU9gS5eEYbT8Sh1tStv5IK9qf.jpg",
		videoId: "QH09YCtpKaw",
		type: "movie",
		duration: "55m",
		trakt: "https://trakt.tv/movies/people-in-motion-2012",
		creators: ["Cedric Dahl"]
	},
	{
		id: 8,
		title: "My Playground",
		year: "2009",
		description: "Mainly set in Copenhagen the film follows Team JiYo as they explore the city and encounter the obstacles it presents.",
		thumbnail: "https://image.tmdb.org/t/p/original/1jHKoGP6NPbnzmf73dvynENdWzr.jpg",
		videoId: "BX-KFdI4LG8",
		type: "movie",
		duration: "52m",
		trakt: "https://trakt.tv/movies/my-playground-2009"
	},
	{
		id: 9,
		title: "Project Pilgrimage",
		year: "2008",
		description: "A documentary by Duncan Germain A.K.A TK17 following his journey to and around Lisses, the birthplace of Parkour. It contains footage of 150+ traceurs, and was shown to David Belle for approval before release.",
		thumbnail: "/images/posters/project-pilgrimage-poster.webp",
		videoId: "M2sWvgsEXeU",
		type: "movie",
		duration: "1h 30m",
		creators: ["Duncan Germain"],
	},
	{
		id: 10,
		title: "Storror Supertramps - Thailand",
		year: "2015",
		description: "Seven parkour athletes roam Southeast Asia for 28 days with no plans, money, or accommodation—capturing a feature-length adventure about freedom and pushing limits.",
		thumbnail: "https://image.tmdb.org/t/p/original/i8Fxvtool5SsqKkatpAsAxCliNJ.jpg",
		externalUrl: "https://storrorplus.storror.com/programs/supertramps-thailand",
		paid: true,
		provider: "STORROR+",
		price: "€6",
		type: "movie",
		duration: "1h 9m",
		trakt: "https://trakt.tv/movies/storror-supertramps-thailand-2015",
		creators: ["STORROR"]
	},
	{
		id: 11,
		title: "GATECRASHER: An All-Women’s Parkour Action Film",
		year: "2024",
		description: "“Gatecrashers” is an all-women Parkour action film following 8 athletes across three European cities. It celebrates female Parkour at its highest level—pushing limits, exploring, and inspiring anyone who loves to move or wants to start.",
		thumbnail: "https://image.tmdb.org/t/p/original/lcXONMiYnSF7oks7S9wH3WU31mo.jpg",
		videoId: "4izoWYFmNg0",
		type: "movie",
		duration: "38m",
		trakt: "https://trakt.tv/movies/gatecrasher-an-all-women-s-parkour-action-film-2024"
	},
	{
		id: 12,
		title: "Queen City: Parkour's First All-Female Film",
		year: "2023",
		description: "In August 2021, eight elite women gathered in Denver to train and film parkour, creating a project that reflects their vision of the city and passion for movement.",
		thumbnail: "/images/posters/queen-city-parkour-female-poster.webp",
		videoId: "IC9xmrrNPyY",
		type: "movie",
		duration: "47m"
	},
	{
		id: 13,
		title: "Balancing Organisms",
		year: "2017",
		description: "A poetic documentary following urban athletes as they practice parkour, jumping from roof to roof through the city. Filmmaker Juriën Cornelissen captures the physical experience and adventure in this graduation film.",
		thumbnail: "/images/posters/balancing-organisms-convoi-films-parkour-poster.webp",
		vimeoId: "223802198",
		type: "movie",
		duration: "28m"
	},
	{
		id: 14,
		title: "Génération Yamakasi",
		year: "2006",
		description: "Dive into the Art of Displacement! Yamakasi transform Paris’s suburbs into playgrounds, inspiring youth with discipline and will. As it becomes an extreme sport, will its social message survive?",
		thumbnail: "https://image.tmdb.org/t/p/original/1uvjUh8lcPuUCk4qW2K6dhT534m.jpg",
		videoId: "0GyxTe9W_yI",
		type: "movie",
		duration: "1h 11m",
		trakt: "https://trakt.tv/movies/generation-yamakasi-2006"
	},
	{
		id: 15,
		title: "District B13",
		year: "2004",
		description: "Set in the ghettos of Paris in 2010, an undercover cop and ex-thug try to infiltrate a gang in order to defuse a neutron bomb.",
		thumbnail: "https://image.tmdb.org/t/p/original/rEfjLYSQHf1EA83vqNPP1KV3Dp6.jpg",
		type: "movie",
		duration: "1h 24m",
		trakt: "https://trakt.tv/movies/district-b13-2004",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/b13"
	},
	{
		id: 16,
		title: "District 13: Ultimatum",
		year: "2009",
		description: "Damien and Leito return to District 13 on a mission to bring peace to the troubled sector that is controlled by five different gang bosses, before the city’s secret services take drastic measures to solve the problem.",
		thumbnail: "https://image.tmdb.org/t/p/original/8okAUSzfWiudSYMXLJYBnlcILcz.jpg",
		type: "movie",
		duration: "1h 41m",
		trakt: "https://trakt.tv/movies/district-13-ultimatum-2009",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/district-b13-ultimatum"
	},
	{
		id: 17,
		title: "Tracers",
		year: "2015",
		description: "A NYC bike messenger, hunted by the mob, dives into an underground parkour crew that offers a risky way out.",
		thumbnail: "https://image.tmdb.org/t/p/original/2XoazCkD4gRlqkJK7q6TOTUx1ta.jpg",
		type: "movie",
		duration: "1h 34m",
		trakt: "https://trakt.tv/movies/tracers-2015",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/tracers"
	},
	{
		id: 18,
		title: "Brick Mansions",
		year: "2014",
		description: "An undercover cop and an ex-con with parkour skills team up to stop a crime lord’s bomb plot in walled-off Detroit.",
		thumbnail: "https://image.tmdb.org/t/p/original/6OopiNRk7lWP0hPsY0eYqq2kQTi.jpg",
		type: "movie",
		duration: "1h 30m",
		trakt: "https://trakt.tv/movies/brick-mansions-2014",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/brick-mansions"
	},
	{
		id: 19,
		title: "6 Underground",
		year: "2019",
		description: "A dead-on-paper billionaire forms a covert parkour-savvy vigilante squad to topple a brutal dictator.",
		thumbnail: "https://image.tmdb.org/t/p/original/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg",
		type: "movie",
		duration: "2h 8m",
		trakt: "https://trakt.tv/movies/6-underground-2019",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/6-underground"
	},
	{
		id: 20,
		title: "Freerunner",
		year: "2011",
		description: "With an explosive collar ticking down, a freerunner sprints across the city battling rivals to save himself and his girlfriend.",
		thumbnail: "https://image.tmdb.org/t/p/original/uy1FNiDvSqUkAKkQ7Nvb42ntdfr.jpg",
		type: "movie",
		duration: "1h 27m",
		trakt: "https://trakt.tv/movies/freerunner-2011",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/freerunner"
	},
	{
		id: 21,
		title: "From Here to There",
		year: "2015",
		description: "Road trip documentary following Jesse La Flair and Cory DeMeyers chasing their freerunning ambitions across the US.",
		thumbnail: "https://image.tmdb.org/t/p/original/2YuDZjJxDn3XV5Ju7RtylWu7VXM.jpg",
		type: "movie",
		duration: "1h",
		trakt: "https://trakt.tv/movies/from-here-to-there-2015",
		paid: true,
		provider: "TV Guide",
		externalUrl: "https://www.tvguide.com/movies/from-here-to-there/2030325953/"
	},
	{
		id: 22,
		title: "Bound By Movement",
		year: "2019",
		description: "“Bound by Movement” follows top parkour athletes on a 63-day U.S. tour, risking injury and arrest to film daring flips and tricks in iconic spots and abandoned buildings, revealing the drive that unites them until things inevitably go wrong.",
		thumbnail: "https://image.tmdb.org/t/p/original/gqblO1Yaeuu3G2WBYsEghxx30EB.jpg",
		type: "movie",
		duration: "1h 22m",
		trakt: "https://trakt.tv/movies/bound-by-movement-2019",
		videoId: "o3-B5EH0mDE"
	},
	{
		id: 23,
		title: "Capstone: The England Project",
		year: "2022",
		description: "Showcase of UK parkour talent pushing creative and powerful new directions following the original Capstone project.",
		thumbnail: "https://image.tmdb.org/t/p/original/pFGNaarSN94MxGTznyW3m4KINL4.jpg",
		videoId: "fv4lg1TfKIA",
		type: "movie",
		duration: "17m",
		trakt: "https://trakt.tv/movies/capstone-the-england-project-2022"
	},
	{
		id: 24,
		title: "Run",
		year: "2013",
		description: "A street-smart 17-year-old parkour thief faces a dangerous past while trying to protect his family.",
		thumbnail: "https://image.tmdb.org/t/p/original/lcEOVoHUyfcMCjciOWikPLWPK0Z.jpg",
		type: "movie",
		duration: "1h 46m",
		trakt: "https://trakt.tv/movies/run-2013",
		paid: true,
		externalUrl: "https://www.justwatch.com/us/movie/run-2013",
		provider: "JustWatch"
	},
	{
		id: 25,
		title: "What Happened",
		year: "2017",
		description: "MYRM's documentary style film featuring the views and moves of several influential parkour practitioners.",
		thumbnail: "/images/posters/what-happened-myrm-parkour-documentary.webp",
		type: "movie",
		duration: "37m",
		videoId: "Ncw1cIaJg4M",
		creators: ["MYRM"],
		starring: ["Callum Powell", "Dante Grazioli", "Juho Kuusisaari", "Brandon Douglass", "Dylan Baker", "Kie Willis", "Joe Hougaard", "Phil Doyle", "Max Henry"]
	}
];
