import { t } from "svelte-i18n";

export const movies = [
	{
		id: 1,
		title: "Jump London",
		year: "2003",
		description: "The documentary that introduced parkour to the world, featuring Sébastien Foucan and other founding traceurs.",
		thumbnail: "https://image.tmdb.org/t/p/original/mSknYoFSBB6o8HeeCTojq3CERgd.jpg",
		videoId: "l8fSXGP9wvQ",
		type: "movie",
		duration: "60m",
		trakt: "https://trakt.tv/movies/jump-london-2003",
		creators: ["Channel 4", "Mike Christie"],
		starring: ["Sébastien Foucan"]
	},
	{
		id: 2,
		title: "Jump Britain",
		year: "2005", 
		description: "The follow-up to Jump London, showcasing British traceurs and the growth of parkour in the UK.",
		thumbnail: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eTMM80n6xFiCwUdNYHEnxEP5QWb.jpg",
		videoId: "2TJurAP9l-Q",
		type: "movie",
		duration: "60m",
		trakt: "https://trakt.tv/movies/jump-britain-2005",
		creators: ["Channel 4", "Mike Christie"],
		starring: ["Sébastien Foucan"]
	},
	{
		id: 3,
		title: "Sole Destroyer",
		year: "2020",
		description: "The Motus Projects athletes push their physical and mental limits in this raw documentary about the evolving sport of parkour. Through elation, stress, injury and laughter, their friendship drives their success.",
		thumbnail: "https://image.tmdb.org/t/p/original/bizGkp2qchu73MNy9Vlh4KW7pQK.jpg",
		videoId: "VlM7bOegiIg",
		type: "movie",
		duration: "40m",
		trakt: "https://trakt.tv/movies/sole-destroyer-2020",
		creators: ["The Motus Projects", "Giles Campbell Longley"],
		starring: [
			"Kelan Ryan",
			"Jordan Tyler Lea",
			"Johnstone Macpherson-Stewart",
			"Luke Stones",
			"George McGowan",
			"Joseph Marx",
			"Robbie Griffith",
			"Max Barker"
		]
	},
	{
		id: 4,
		title: "Amsterdam Is Dead",
		year: "2024",
		description: "AMSTERDAM IS DEAD a Parkour Film aiming to revive this city's lost street parkour scene. Documentaire door Fé Amsterdam.",
		thumbnail: "https://image.tmdb.org/t/p/original/8jJ0IEc24tC1w24niLc2c343YPi.jpg",
		videoId: "lJX3DUlSj4M",
		type: "movie",
		duration: "48m",
		trakt: "https://trakt.tv/movies/amsterdam-is-dead-2024",
		creators: ["Fé Amsterdam", "Safier Elzinga", "Dave Alvar"],
		starring: [
			"Jan Simon",
			"Naël Saint-Paul",
			"Twan de Wilde",
			"Maurits Dorren",
			"Safier Elzinga",
			"Sjoerd Rensma",
			"Bram Looijen",
			"Abel Marce",
			"Vic Kooy",
			"Wieger Hoekstra",
			"Liziano Ostina",
			"Silver Moscou",
			"Francesco Kamstra",
			"Dave Alvar",
			"Tobias Roest"
		]
	},
	{
		id: 5,
		title: "Roof Culture Asia",
		year: "2017",
		description: "Team Storror push Parkour to the rooftops of Asian megacities, filming guerilla-style while exploring the drive, struggles, and preparation behind making impossible \"leaps of faith\" possible.",
		thumbnail: "https://image.tmdb.org/t/p/original/aeAe6WOKXROmmXySeZN6dWccWPX.jpg",
		externalUrl: "https://storrorplus.storror.com/programs/rca?cid=4256061",
		paid: true,
		provider: "STORROR+",
		price: "€8",
		type: "movie",
		duration: "1h 53m",
		trakt: "https://trakt.tv/movies/roof-culture-asia-2017",
		creators: ["STORROR"],
		starring: [
			"Benj Cave",
			"Toby Segar",
			"Max Cave",
			"Callum Powell",
			"Sacha Powell",
			"Richard Ferreday",
			"Drew Taylor",
			"Joshua Burnett-Blake",
			"Giles Campbell Longley"
		]
	},
	{
		id: 6,
		title: "S.O.L",
		year: "2022",
		description: "S.O.L is a parkour tour film with the carefree vibe of 2010s summer edits, focusing less on moves and more on friendship, support, and shared training moments.",
		thumbnail: "/images/posters/the-motus-projects-sol-poster.webp",
		videoId: "Tswad8jCgaM",
		type: "movie",
		duration: "1h 12m",
		creators: ["The Motus Projects", "Max Barker", "Kelan Ryan", "Sam Sutherland"],
		starring: [
			"Travis Verkaik",
			"Rachel Gough",
			"Ethan Rudd",
			"Joseph Marx",
			"Sam Sutherland",
			"Kelan Ryan",
			"Johnstone Macpherson-Stewart",
			"George McGowan",
			"Max Barker",
			"Robbie Griffith"
		]
	},
	{
		id: 7,
		title: "People in Motion",
		year: "2012",
		description: "Cedric Dahl traveled the US west coast with 5 parkour practitioners who shared a passion for movement. This film documents the experience over 9 months.",
		thumbnail: "https://image.tmdb.org/t/p/original/4WiU9gS5eEYbT8Sh1tStv5IK9qf.jpg",
		videoId: "QH09YCtpKaw",
		type: "movie",
		duration: "55m",
		trakt: "https://trakt.tv/movies/people-in-motion-2012",
		creators: ["Cedric Dahl", "Ben Hoffman"],
		starring: [
			"Jacob Seil",
			"Paul Whitecotton",
			"David Agajanian",
			"Brian Orosco",
			"Lonnie Tisdale"
		]
	},
	{
		id: 8,
		title: "My Playground",
		year: "2009",
		description: "Mainly set in Copenhagen the film follows Team JiYo as they explore the city and encounter the obstacles it presents.",
		thumbnail: "https://image.tmdb.org/t/p/original/1jHKoGP6NPbnzmf73dvynENdWzr.jpg",
		videoId: "BX-KFdI4LG8",
		type: "movie",
		duration: "52m",
		trakt: "https://trakt.tv/movies/my-playground-2009",
		creators: ["Kaspar Astrup Schröder"],
		starring: [
			"Team, JiYo",
			"Big Archtects",
			"Team Frazy",
			"Team PKTK",
			"American Parkour",
			"Tim 'Livewire' Shieff",
			"Ryan Doyle"
		]
	},
	{
		id: 9,
		title: "Project Pilgrimage",
		year: "2008",
		description: "A documentary following his journey to and around Lisses, the birthplace of Parkour. It contains footage of 150+ traceurs, and was shown to David Belle for approval before release.",
		thumbnail: "/images/posters/project-pilgrimage-poster.webp",
		videoId: "M2sWvgsEXeU",
		type: "movie",
		duration: "1h 30m",
		creators: ["Duncan Germain A.K.A TK17"],
	},
	{
		id: 10,
		title: "Storror Supertramps - Thailand",
		year: "2015",
		description: "Seven parkour athletes roam Southeast Asia for 28 days with no plans, money, or accommodation—capturing a feature-length adventure about freedom and pushing limits.",
		thumbnail: "https://image.tmdb.org/t/p/original/i8Fxvtool5SsqKkatpAsAxCliNJ.jpg",
		externalUrl: "https://storrorplus.storror.com/programs/supertramps-thailand",
		paid: true,
		provider: "STORROR+",
		price: "€6",
		type: "movie",
		duration: "1h 9m",
		trakt: "https://trakt.tv/movies/storror-supertramps-thailand-2015",
		creators: ["STORROR"],
		starring: [
			"Benj Cave",
			"Toby Segar",
			"Max Cave",
			"Callum Powell",
			"Sacha Powell",
			"Steven Whitely",
			"Drew Taylor"
		]
	},
	{
		id: 11,
		title: "GATECRASHER: An All-Women’s Parkour Action Film",
		year: "2024",
		description: "“Gatecrashers” is an all-women Parkour action film following 8 athletes across three European cities. It celebrates female Parkour at its highest level—pushing limits, exploring, and inspiring anyone who loves to move or wants to start.",
		thumbnail: "https://image.tmdb.org/t/p/original/lcXONMiYnSF7oks7S9wH3WU31mo.jpg",
		videoId: "4izoWYFmNg0",
		type: "movie",
		duration: "38m",
		trakt: "https://trakt.tv/movies/gatecrasher-an-all-women-s-parkour-action-film-2024",
		creators: ["Point A Parkour", "Renae Dambly", "Lisa Schneider", "KIDA"],
		starring: [
			"Tamila Benabdallah",
			"Elise Bickley",
			"Renae Dambly",
			"Lisa Eckert",
			"Rachel Gough",
			"Hazal Nehir",
			"Lilou Ruel",
			"Lisa Schneider",
			"Camila Stefaniu",
			"Louisa Chang",
			"Stanislava Kirilova"
		]
	},
	{
		id: 12,
		title: "Queen City: Parkour's First All-Female Film",
		year: "2023",
		description: "In August 2021, eight elite women gathered in Denver to train and film parkour, creating a project that reflects their vision of the city and passion for movement.",
		thumbnail: "/images/posters/queen-city-parkour-female-poster.webp",
		videoId: "IC9xmrrNPyY",
		type: "movie",
		duration: "47m",
		creators: ["Point A Parkour", "Max Henry", "Sean Endres"],
		starring: [
			"Tamila Benabdallah",
			"Kristine Dietrich",
			"Sara Mudallal",
			"Kira Nguyen",
			"Sydney Olson",
			"Seneca Schwartz",
			"Alyssa Serpa",
			"Sheep"
		]
	},
	{
		id: 13,
		title: "Balancing Organisms",
		year: "2017",
		description: "A poetic documentary following urban athletes as they practice parkour, jumping from roof to roof through the city. Filmmaker Juriën Cornelissen captures the physical experience and adventure in this graduation film.",
		thumbnail: "/images/posters/balancing-organisms-convoi-films-parkour-poster.webp",
		vimeoId: "223802198",
		type: "movie",
		duration: "28m",
		creators: ["Juriën Cornelissen", "Convoi Films"],
		starring: [
			"Luciano Balestra",
			"Phil Doyle"
		]
	},
	{
		id: 14,
		title: "Génération Yamakasi",
		year: "2006",
		description: "Dive into the Art of Displacement! Yamakasi transform Paris’s suburbs into playgrounds, inspiring youth with discipline and will. As it becomes an extreme sport, will its social message survive?",
		thumbnail: "https://image.tmdb.org/t/p/original/1uvjUh8lcPuUCk4qW2K6dhT534m.jpg",
		videoId: "0GyxTe9W_yI",
		type: "movie",
		duration: "1h 11m",
		trakt: "https://trakt.tv/movies/generation-yamakasi-2006"
	},
	{
		id: 15,
		title: "District B13",
		year: "2004",
		description: "Set in the ghettos of Paris in 2010, an undercover cop and ex-thug try to infiltrate a gang in order to defuse a neutron bomb.",
		thumbnail: "https://image.tmdb.org/t/p/original/rEfjLYSQHf1EA83vqNPP1KV3Dp6.jpg",
		type: "movie",
		duration: "1h 24m",
		trakt: "https://trakt.tv/movies/district-b13-2004",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/b13",
		creators: ["Pierre Morel"],
		starring: ["David Belle"]
	},
	{
		id: 16,
		title: "District 13: Ultimatum",
		year: "2009",
		description: "Damien and Leito return to District 13 on a mission to bring peace to the troubled sector that is controlled by five different gang bosses, before the city’s secret services take drastic measures to solve the problem.",
		thumbnail: "https://image.tmdb.org/t/p/original/8okAUSzfWiudSYMXLJYBnlcILcz.jpg",
		type: "movie",
		duration: "1h 41m",
		trakt: "https://trakt.tv/movies/district-13-ultimatum-2009",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/district-b13-ultimatum",
		creators: ["Patrick Alessandrin"],
		starring: ["David Belle"]
	},
	{
		id: 17,
		title: "Tracers",
		year: "2015",
		description: "A NYC bike messenger, hunted by the mob, dives into an underground parkour crew that offers a risky way out.",
		thumbnail: "https://image.tmdb.org/t/p/original/2XoazCkD4gRlqkJK7q6TOTUx1ta.jpg",
		type: "movie",
		duration: "1h 34m",
		trakt: "https://trakt.tv/movies/tracers-2015",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/tracers",
		creators: ["Daniel Benmayor"],
		starring: ["Taylor Lautner"]
	},
	{
		id: 18,
		title: "Brick Mansions",
		year: "2014",
		description: "An undercover cop and an ex-con with parkour skills team up to stop a crime lord’s bomb plot in walled-off Detroit.",
		thumbnail: "https://image.tmdb.org/t/p/original/6OopiNRk7lWP0hPsY0eYqq2kQTi.jpg",
		type: "movie",
		duration: "1h 30m",
		trakt: "https://trakt.tv/movies/brick-mansions-2014",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/brick-mansions",
		creators: ["Camille Delamarre"],
		starring: ["David Belle", "Paul Walker"]
	},
	{
		id: 19,
		title: "6 Underground",
		year: "2019",
		description: "A dead-on-paper billionaire forms a covert parkour-savvy vigilante squad to topple a brutal dictator.",
		thumbnail: "https://image.tmdb.org/t/p/original/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg",
		type: "movie",
		duration: "2h 8m",
		trakt: "https://trakt.tv/movies/6-underground-2019",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/6-underground",
		creators: ["Michael Bay"],
		starring: ["Ryan Reynolds"]

	},
	{
		id: 20,
		title: "Freerunner",
		year: "2011",
		description: "With an explosive collar ticking down, a freerunner sprints across the city battling rivals to save himself and his girlfriend.",
		thumbnail: "https://image.tmdb.org/t/p/original/uy1FNiDvSqUkAKkQ7Nvb42ntdfr.jpg",
		type: "movie",
		duration: "1h 27m",
		trakt: "https://trakt.tv/movies/freerunner-2011",
		paid: true,
		provider: "JustWatch",
		externalUrl: "https://www.justwatch.com/us/movie/freerunner",
		creators: ["Lawrence Silverstein"],
		starring: ["Sean Faris"]
	},
	{
		id: 21,
		title: "From Here to There",
		year: "2015",
		description: "Road trip documentary following Jesse La Flair and Cory DeMeyers chasing their freerunning ambitions across the US.",
		thumbnail: "https://image.tmdb.org/t/p/original/2YuDZjJxDn3XV5Ju7RtylWu7VXM.jpg",
		type: "movie",
		duration: "1h",
		trakt: "https://trakt.tv/movies/from-here-to-there-2015",
		paid: true,
		provider: "TV Guide",
		externalUrl: "https://www.tvguide.com/movies/from-here-to-there/2030325953/",
		creators: ["Spinning Owls Productions", "Concrete Collective", "La Flair Films"],
		starring: ["Jesse La Flair", "Cory DeMeyers", "Anan Anwar", "Brienne La Flair", "Gabriel Nunez"]
	},
	{
		id: 22,
		title: "Bound By Movement",
		year: "2019",
		description: "“Bound by Movement” follows top parkour athletes on a 63-day U.S. tour, risking injury and arrest to film daring flips and tricks in iconic spots and abandoned buildings, revealing the drive that unites them until things inevitably go wrong.",
		thumbnail: "https://image.tmdb.org/t/p/original/gqblO1Yaeuu3G2WBYsEghxx30EB.jpg",
		type: "movie",
		duration: "1h 22m",
		trakt: "https://trakt.tv/movies/bound-by-movement-2019",
		videoId: "o3-B5EH0mDE",
		creators: ["Jesse La Flair"],
		starring: [
			"Jesse La Flair",
			"Sydney Olson",
			"Corbin Reinhardt"
		]
	},
	{
		id: 23,
		title: "Capstone: The England Project",
		year: "2022",
		description: "Showcase of UK parkour talent pushing creative and powerful new directions following the original Capstone project.",
		thumbnail: "https://image.tmdb.org/t/p/original/pFGNaarSN94MxGTznyW3m4KINL4.jpg",
		videoId: "fv4lg1TfKIA",
		type: "movie",
		duration: "17m",
		trakt: "https://trakt.tv/movies/capstone-the-england-project-2022",
		creators: ["CAPST1"],
		starring: [	
			"Toby Segar",
			"Travis Verkaik",
			"Philip Doyle",
			"Jannis Schauer",
			"Joe Scandrett",
			"Ed Scott"
		]
	},
	{
		id: 24,
		title: "Run",
		year: "2013",
		description: "A street-smart 17-year-old parkour thief faces a dangerous past while trying to protect his family.",
		thumbnail: "https://image.tmdb.org/t/p/original/lcEOVoHUyfcMCjciOWikPLWPK0Z.jpg",
		type: "movie",
		duration: "1h 46m",
		trakt: "https://trakt.tv/movies/run-2013",
		paid: true,
		externalUrl: "https://www.justwatch.com/us/movie/run-2013",
		provider: "JustWatch",
		creators: ["Spinning Owls Productions", "224 Entertainment", "Simone Bartesaghi"]
	},
	{
		id: 25,
		title: "What Happened",
		year: "2017",
		description: "MYRM's documentary style film featuring the views and moves of several influential parkour practitioners.",
		thumbnail: "/images/posters/what-happened-myrm-parkour-documentary.webp",
		type: "movie",
		duration: "37m",
		videoId: "Ncw1cIaJg4M",
		creators: ["MYRM"],
		starring: ["Callum Powell", "Dante Grazioli", "Juho Kuusisaari", "Brandon Douglass", "Dylan Baker", "Kie Willis", "Joe Hougaard", "Phil Doyle", "Max Henry"]
	},
	{
		id: 26,
		title: "Quality Control",
		year: "2021",
		description: "Months of filming have been put together in the hopes of capturing the Swedish parkour scene and the general vibe we have whilst training.",
		thumbnail: "/images/posters/quality-control-swedish-parkour-documentary.webp",
		type: "movie",
		duration: "35m",
		videoId: "ifr0XZjuG3Q",
		creators: ["KIPA"],
		starring: ["Kevin Franzén", "Hugo Arnesson", "Miranda Tibbling", "Matar Gaza", "Murat Alishev", "Joel Larsson", "Lester Castro", "Matar Gaza"]
	},
	{
		id: 27,
		title: "state Of miNd",
		year: "2023",
		description: "A documentary about living permanently switched ON. A mindset where fear fades and passion takes over—driving you to create, move, and push limits every day.",
		thumbnail: "/images/posters/sick-mode-state-Of-miNd-poster-parkour.webp",
		type: "movie",
		duration: "14m",
		videoId: "cZMb7SeUnvk",
		creators: ["Sick Mode", "Kamil Tobiasz", "Flying Carpet Studio"],
		starring: ["Kamil Półtorak", "Oskar Opatowski", "Kacper Kośmider", "Miłosz Jarmołowicz", "Kacper Lipski", "Dawid Zakrzewski", "Konrad Kapek", "Mateusz Petryszyn"]
	},
	{
		id: 28,
		title: "CRACKSTONE",
		year: "2023",
		description: "Grassroots GEFAM-funded parkour film inspired by Capst1, spotlighting the creative flip side of movement. Filmed in Frankfurt, the name stuck after an inside joke about the city's rough edges—capturing a raw, collaborative energy the crew hopes to build on.",
		thumbnail: "/images/posters/gefam-crackstone-parkour-film-poster.webp",
		videoId: "4n4Lr0yoTNc",
		type: "movie",
		duration: "36m",
		creators: ["Luca Beaufort", "Safier Elzinga", "GEFAM", "Francesco Kamstra", "Sjoerd Rensma"],
		starring: [
			"Amir Kaiser",
			"Laurenz Weeke",
			"Josef Vyhlas",
			"Lukas Divis",
			"Safier Elzinga",
			"Sjoerd Rensma",
			"Ryuya Kuwasaki",
			"Zoe Kern",
			"Francesco Kamstra",
			"Tobias Roest",
			"Ryuya Shirai"
		]
	},
	{
		id: 29,
		title: "Hazel",
		year: "2022",
		description: "Hazel marks Ethan Rud’s 10 years of parkour, channeling grief after a mentor’s loss. Filmed in Minneapolis and Los Angeles by Noah Heath, it’s a dark, moody street video paving the way for shorter pay-per-view films.",
		thumbnail: "/images/posters/the-motus-projects-hazel-poster-freerunning.webp",
		videoId: "EvJGWvXrINw",
		type: "movie",
		duration: "10m",
		creators: ["The Motus Projects", "Noah Heath"],
		starring: ["Ethan Rud"]
	},
	{
		id: 30,
		title: "SABAI SABAI",
		year: "2023",
		description: "This film is very fine! It shows the beauty of parkour in Thailand, combining stunning locations with smooth movement and a chilled vibe.",
		thumbnail: "/images/posters/sabai-sabai-parkour-freerunning-movie-poster.webp",
		videoId: "DKZ-bt2oaic",
		type: "movie",
		duration: "23m",
		creators: ["GEFAM", "Julius Klein", "Lucas Siehl", "Simon Pronk"],
		starring: [
			"Julius Klein",
			"Simon Pronk",
			"Jovan Uljarevic",
			"Luca Beaufort",
			"Lucas Siehl",
			"Yoojin Lee",
			"Jonas Rosenberg",
			"Valentin Huwer"
		]
	},
	{
		id: 31,
		title: "RUNNING A FAMILY",
		year: "2023",
		description: "Commit's documentary about the power of a community. Highlighting the parkour community in Eindhoven, by showing the stories of their team members.", 
		thumbnail: "/images/posters/running-a-family-commit-freerun-documentary.webp",
		videoId: "i9Zq7oT5Cvw",
		type: "movie",
		duration: "22m",
		creators: [
			"Studio Lafo",
			"Lumens",
			"Lars Cleven",
			"Tommy Köhlbrugge",
			"Stef Cleven",
			"Jeroen Schreiner",
			"Omar Malasi",
			"Dutch Drone Gods",
			"Gijs van Os",
			"Cas Oerlemans",
			"Nabil El Hamdaoui",
			"Colin Dust",
			"Brend Kuppers",
			"Luke Linssen",
			"Commit Freerun"
		],
		starring: [
			"Johan Vereijken",
			"Bart van der Linden",
			"Jeroen Schreiner",
			"Hidde Martens",
			"Siebe van de Spijker",
			"Lisa Eckert",
			"Joe Scandrett",
			"Marc Busch",
			"Drew Taylor"
		]
	}
];
